import {Project} from '@/components/RecentHighlights';

export const postData = {
    title: 'React Performance Optimization',
    slug: '/posts/react-performance',
    excerpt: 'Common performance optimizations and dealing with large datasets',
    date: '2025-08-10',
    readingTime: '6 min',
    coverImage: '/projects/performance.png',
    tags: ['React', 'Performance', 'Big Data'],
};

export const projectData = [
    {
        name: 'AAC Component Library',
        // slug: 'https://bvh-data-viewer.vercel.app',
        blurb: "I created this storybook application to house all of AAC's internal components, which were used across 20 different Next.js applications. Testing was done mostly through React Testing Library and Code coverage was monitored via Github Action",
        date: '2025-08-01',
        stack: ['Storybook', 'React', 'Express', 'S3'],
        coverImage: '/projects/cl.png',
        // liveUrl: 'https://bvh-data-viewer.vercel.app',
        // repoUrl: 'https://github.com/pbarera1/bvh-data-viewer',
        label: 'Frontend',
    },
    {
        name: 'AAC Marketing Sites',
        slug: 'https://bvh-data-viewer.vercel.app',
        blurb: '12 Next.js application that pulled data from headless CMS via the Wordpress REST api. The 12 sites were split between 4 product teams, seo and performance optimization were critical. Some domains include <a href="https://rehabs.com">Rehabs.com<a/>, <a href="https://americanaddictioncenters.org/">AmericanAddictionCenters.org<a/>, <a href="https://lagunatreatment.com/">LagunaTreatment.com/<a/>',
        date: '2025-08-01',
        stack: ['Next.js', 'Express', 'AWS', 'Headless Wordpress', 'MySQL'],
        coverImage: '/projects/rehabs.png',
        liveUrl: 'https://bvh-data-viewer.vercel.app',
        repoUrl: 'https://github.com/pbarera1/bvh-data-viewer',
        label: 'Fullstack',
    },
    {
        name: 'AAC Internal Tooling',
        slug: 'https://bvh-data-viewer.vercel.app',
        blurb: "This site served as a house for multiple internal tools--some included; a GUI for adding Nginx redirects to a site, a CRUD app for creating and monitoring dynamic QR codes, a GUI for facility features and it's API that was consumed by the web portfolio, and the version status of shared code repos across sites.",
        date: '2025-08-01',
        stack: ['Next.js', 'Auth.js', 'MongoDB', 'Mongoose'],
        coverImage: '/projects/cp.png',
        liveUrl: 'https://bvh-data-viewer.vercel.app',
        repoUrl: 'https://github.com/pbarera1/bvh-data-viewer',
        label: 'Fullstack',
    },
    {
        name: 'AAC Multi-Step AI Insurance Form',
        slug: 'https://bvh-data-viewer.vercel.app',
        blurb: 'The form would allow a user to upload or snap a photo of an insurance card. That card would then be sent to the Gemini API where insurance data was pulled from the card and autofilled into different steps of the form, saving user time rom entering in long policy numbers.',
        date: '2025-08-01',
        stack: ['React', 'Gemini API', 'Canvas'],
        coverImage: '/projects/vob-autofill.mp4',
        liveUrl: 'https://bvh-data-viewer.vercel.app',
        repoUrl: 'https://github.com/pbarera1/bvh-data-viewer',
        label: 'Frontend',
    },
    {
        name: 'Workout and Nutrition PWA',
        slug: 'https://workoutnow.org',
        blurb: 'This PWA allows users to create many different styles of workout and custom mealplans. Some of the challenges were drag-and-drop reordering of exercises and video file compression',
        date: '2025-08-01',
        stack: ['Next.js', 'Redux', 'Firestore', 'S3'],
        coverImage: '/projects/workoutnow.png',
        liveUrl: 'https://workoutnow.org',
        repoUrl: 'https://github.com/pbarera1/bvh-data-viewer',
        label: 'Fullstack',
    },
    {
        name: 'AAC Advertising Application',
        slug: 'https://clientreachapp.recoverybrands.com/login',
        blurb: 'The Clientreach application is the top advertising platform in the addiction space. It is used to buy adspace and view analytics',
        date: '2025-08-01',
        stack: ['Next.js', 'Redux', 'PostgreSQL', 'AWS'],
        coverImage: '/projects/cr.png',
        liveUrl: 'https://clientreachapp.recoverybrands.com/login',
        // repoUrl: 'https://github.com/pbarera1/bvh-data-viewer',
        label: 'Frontend',
    },
    {
        name: 'AAC Geolocation API',
        slug: 'https://bvh-data-viewer.vercel.app',
        blurb: 'Using maxmind ip4 and ip6 data, this API allows us to get the lat/long and closest town for a user. We would then change the global state of our application to show user things like the closest geographic Rwhab facility',
        date: '2025-08-01',
        stack: ['Express', 'MongoDB', 'AWS', 'Redis'],
        coverImage: '/projects/geolocation.mp4',
        // liveUrl: 'https://bvh-data-viewer.vercel.app',
        // repoUrl: 'https://github.com/pbarera1/bvh-data-viewer',
        label: 'Backend',
    },
    {
        name: 'BVH Data Viewer',
        slug: 'https://bvh-data-viewer.vercel.app',
        blurb: 'View select motion capture Biovision Hierarchy datasets from a basketball player.',
        date: '2025-08-14',
        stack: ['Three.js', 'React', 'Vite', 'Vercel'],
        coverImage: '/bball.png',
        liveUrl: 'https://bvh-data-viewer.vercel.app',
        repoUrl: 'https://github.com/pbarera1/bvh-data-viewer',
        label: 'Frontend',
    },
    {
        name: 'AAC Native App for Alumni',
        slug: 'https://bvh-data-viewer.vercel.app',
        blurb: 'This React Native/Expo app was the result of a developer week initiative. It served as a POC for future React NAtive projects and an intro for the frontend team into mobile apps.',
        date: '2025-08-01',
        stack: ['React Native', 'Expo'],
        coverImage: '/projects/alumni-1.mp4',
        liveUrl: 'https://bvh-data-viewer.vercel.app',
        repoUrl: 'https://github.com/pbarera1/bvh-data-viewer',
        label: 'Frontend',
    },
];
