import {Project} from '@/components/RecentHighlights';

export const postData = {
    title: 'React Performance Optimization',
    slug: '/posts/react-performance',
    excerpt:
        'Common performance optimizations and strategies for handling large datasets.',
    date: '2025-08-10',
    readingTime: '6 min',
    coverImage: '/projects/performance.png',
    tags: ['React', 'Performance', 'Big Data'],
};

export const projectData = [
    {
        name: 'AAC Component Library',
        slug: '',
        blurb: "I created this Storybook application to house all of AAC's internal components, which were shared across 20 different Next.js applications. Testing was primarily done with React Testing Library, and code coverage was monitored through GitHub Actions.",
        date: '2025-08-01',
        stack: ['Storybook', 'React', 'Express', 'S3'],
        coverImage: '/projects/cl.png',
        label: 'Frontend',
    },
    {
        name: 'AAC Marketing Sites',
        slug: 'https://rehabs.com',
        blurb: 'A suite of 12 Next.js applications pulling content from a headless CMS via the WordPress REST API. These sites were divided among four product teams, where SEO and performance optimization were critical. Notable domains included <a href="https://rehabs.com">Rehabs.com</a>, <a href="https://americanaddictioncenters.org/">AmericanAddictionCenters.org</a>, and <a href="https://lagunatreatment.com/">LagunaTreatment.com</a>.',
        date: '2025-08-01',
        stack: ['Next.js', 'Express', 'AWS', 'Headless WordPress', 'MySQL'],
        coverImage: '/projects/rehabs.png',
        // liveUrl: 'https://rehabs.com',
        // repoUrl: 'https://github.com/pbarera1/bvh-data-viewer',
        label: 'Fullstack',
    },
    {
        name: 'AAC Internal Tooling',
        slug: '',
        blurb: 'This site consolidated multiple internal tools, including: a GUI for adding Nginx redirects, a CRUD app for creating and monitoring dynamic QR codes, a facility features editor with its own API (consumed by the web portfolio), and dashboards showing version status of shared repos across sites.',
        date: '2025-08-01',
        stack: ['Next.js', 'Auth.js', 'MongoDB', 'Mongoose'],
        coverImage: '/projects/cp.png',
        // liveUrl: 'https://bvh-data-viewer.vercel.app',
        // repoUrl: 'https://github.com/pbarera1/bvh-data-viewer',
        label: 'Fullstack',
    },
    {
        name: 'AAC Multi-Step AI Insurance Form',
        slug: '',
        blurb: 'This multi-step form allowed users to upload or capture a photo of an insurance card. The card image was processed by the Gemini API to extract insurance details, which were then auto-filled into the form — saving users from manually entering long policy numbers.',
        date: '2025-08-01',
        stack: ['React', 'Gemini API', 'Canvas'],
        coverImage: '/projects/vob-autofill.mp4',
        // liveUrl: 'https://bvh-data-viewer.vercel.app',
        // repoUrl: 'https://github.com/pbarera1/bvh-data-viewer',
        label: 'Frontend',
    },
    {
        name: 'Workout and Nutrition PWA',
        slug: 'https://workoutnow.org/login',
        blurb: 'A progressive web app enabling users to create customized workouts and meal plans. Technical challenges included implementing drag-and-drop reordering of exercises and efficient video file compression.',
        date: '2025-08-01',
        stack: ['Next.js', 'Redux', 'Firestore', 'S3'],
        coverImage: '/projects/workoutnow.png',
        // liveUrl: 'https://workoutnow.org',
        // repoUrl: 'https://github.com/pbarera1/bvh-data-viewer',
        label: 'Fullstack',
    },
    {
        name: 'AAC Advertising Application',
        slug: 'https://clientreachapp.recoverybrands.com/login',
        blurb: 'ClientReach is the leading advertising platform in the addiction recovery space. It allows users to purchase ad space and access detailed analytics.',
        date: '2025-08-01',
        stack: ['Next.js', 'Redux', 'PostgreSQL', 'AWS'],
        coverImage: '/projects/cr.png',
        // liveUrl: 'https://clientreachapp.recoverybrands.com/login',
        label: 'Frontend',
    },
    {
        name: 'AAC Geolocation API',
        slug: 'https://bvh-data-viewer.vercel.app',
        blurb: 'Using MaxMind IPv4/IPv6 data, this API returns a user’s latitude, longitude, and closest city. The global state of our web applications could then adapt, e.g., by showing the nearest rehab facility.',
        date: '2025-08-01',
        stack: ['Express', 'MongoDB', 'AWS', 'Redis'],
        coverImage: '/projects/geolocation.mp4',
        label: 'Backend',
    },
    {
        name: 'BVH Data Viewer',
        slug: 'https://bvh-data-viewer.vercel.app',
        blurb: 'A visualization tool for select Biovision Hierarchy (BVH) motion-capture datasets recorded from a basketball player.',
        date: '2025-08-14',
        stack: ['Three.js', 'React', 'Vite', 'Vercel'],
        coverImage: '/bball.png',
        // liveUrl: 'https://bvh-data-viewer.vercel.app',
        repoUrl: 'https://github.com/pbarera1/bvh-data-viewer',
        label: 'Frontend',
    },
    {
        name: 'AAC Native App for Alumni',
        slug: '',
        blurb: 'A React Native/Expo app built during a developer week initiative. It served as a proof of concept for future mobile projects and introduced the frontend team to native app development.',
        date: '2025-08-01',
        stack: ['React Native', 'Expo'],
        coverImage: '/projects/alumni-1.mp4',
        // liveUrl: 'https://bvh-data-viewer.vercel.app',
        // repoUrl: 'https://github.com/pbarera1/bvh-data-viewer',
        label: 'Frontend',
    },
];
